import { ThemeColors, ThemePreset } from './types';

export const themePresets: Record<ThemePreset, { light: ThemeColors; dark: ThemeColors }> = {
  default: {
    light: {
      primary: '#1a1a1a',
      primaryHover: '#333333',
      primaryForeground: '#ffffff',
      secondary: '#f3f4f6',
      surface: '#f3f4f6',
      surfaceHover: '#e5e7eb',
      border: '#d1d5db',
      text: '#111827',
      textMuted: '#6b7280',
    },
    dark: {
      primary: '#f9fafb',
      primaryHover: '#e5e7eb',
      primaryForeground: '#111827',
      secondary: '#1f2937',
      surface: '#1f2937',
      surfaceHover: '#374151',
      border: '#374151',
      text: '#f9fafb',
      textMuted: '#9ca3af',
    },
  },

  indigo: {
    light: {
      primary: '#4f46e5',
      primaryHover: '#4338ca',
      primaryForeground: '#ffffff',
      secondary: '#e0e7ff',
      secondaryHover: '#c7d2fe',
      secondaryForeground: '#3730a3',
      background: '#ffffff',
      foreground: '#0f172a',
      surface: '#f8fafc',
      surfaceHover: '#f1f5f9',
      border: '#e2e8f0',
      text: '#0f172a',
      textMuted: '#64748b',
      ring: '#6366f1',
    },
    dark: {
      primary: '#6366f1',
      primaryHover: '#818cf8',
      primaryForeground: '#ffffff',
      secondary: '#1e1b4b',
      secondaryHover: '#312e81',
      secondaryForeground: '#e0e7ff',
      background: '#090d16',
      foreground: '#f8fafc',
      surface: '#1e293b',
      surfaceHover: '#334155',
      border: '#334155',
      text: '#f8fafc',
      textMuted: '#94a3b8',
      ring: '#818cf8',
    },
  },

  emerald: {
    light: {
      primary: '#059669',
      primaryHover: '#047857',
      primaryForeground: '#ffffff',
      secondary: '#d1fae5',
      secondaryHover: '#a7f3d0',
      secondaryForeground: '#065f46',
      background: '#ffffff',
      foreground: '#064e3b',
      surface: '#f0fdf4',
      surfaceHover: '#dcfce7',
      border: '#e2e8f0',
      text: '#064e3b',
      textMuted: '#64748b',
      ring: '#10b981',
    },
    dark: {
      primary: '#10b981',
      primaryHover: '#34d399',
      primaryForeground: '#064e3b',
      secondary: '#064e3b',
      secondaryHover: '#047857',
      secondaryForeground: '#d1fae5',
      background: '#022c22',
      foreground: '#ecfdf5',
      surface: '#065f46',
      surfaceHover: '#047857',
      border: '#047857',
      text: '#ecfdf5',
      textMuted: '#a7f3d0',
      ring: '#34d399',
    },
  },

  purple: {
    light: {
      primary: '#7c3aed',
      primaryHover: '#6d28d9',
      primaryForeground: '#ffffff',
      secondary: '#f3e8ff',
      secondaryHover: '#e9d5ff',
      secondaryForeground: '#5b21b6',
      background: '#ffffff',
      foreground: '#1e1b4b',
      surface: '#faf5ff',
      surfaceHover: '#f3e8ff',
      border: '#e9d5ff',
      text: '#1e1b4b',
      textMuted: '#6b7280',
      ring: '#8b5cf6',
    },
    dark: {
      primary: '#8b5cf6',
      primaryHover: '#a78bfa',
      primaryForeground: '#ffffff',
      secondary: '#4c1d95',
      secondaryHover: '#5b21b6',
      secondaryForeground: '#f3e8ff',
      background: '#0f0728',
      foreground: '#faf5ff',
      surface: '#2e1065',
      surfaceHover: '#3b0764',
      border: '#4c1d95',
      text: '#faf5ff',
      textMuted: '#c084fc',
      ring: '#a78bfa',
    },
  },

  ocean: {
    light: {
      primary: '#0284c7',
      primaryHover: '#0369a1',
      primaryForeground: '#ffffff',
      secondary: '#e0f2fe',
      secondaryHover: '#bae6fd',
      secondaryForeground: '#075985',
      background: '#ffffff',
      foreground: '#0c4a6e',
      surface: '#f0f9ff',
      surfaceHover: '#e0f2fe',
      border: '#bae6fd',
      text: '#0c4a6e',
      textMuted: '#64748b',
      ring: '#38bdf8',
    },
    dark: {
      primary: '#38bdf8',
      primaryHover: '#7dd3fc',
      primaryForeground: '#0c4a6e',
      secondary: '#075985',
      secondaryHover: '#0369a1',
      secondaryForeground: '#e0f2fe',
      background: '#082f49',
      foreground: '#f0f9ff',
      surface: '#0c4a6e',
      surfaceHover: '#075985',
      border: '#0369a1',
      text: '#f0f9ff',
      textMuted: '#7dd3fc',
      ring: '#7dd3fc',
    },
  },

  amber: {
    light: {
      primary: '#d97706',
      primaryHover: '#b45309',
      primaryForeground: '#ffffff',
      secondary: '#fef3c7',
      secondaryHover: '#fde68a',
      secondaryForeground: '#78350f',
      background: '#ffffff',
      foreground: '#451a03',
      surface: '#fffbeb',
      surfaceHover: '#fef3c7',
      border: '#fde68a',
      text: '#451a03',
      textMuted: '#78350f',
      ring: '#f59e0b',
    },
    dark: {
      primary: '#f59e0b',
      primaryHover: '#fbbf24',
      primaryForeground: '#451a03',
      secondary: '#78350f',
      secondaryHover: '#92400e',
      secondaryForeground: '#fef3c7',
      background: '#291e0a',
      foreground: '#fffbeb',
      surface: '#451a03',
      surfaceHover: '#78350f',
      border: '#92400e',
      text: '#fffbeb',
      textMuted: '#fcd34d',
      ring: '#fbbf24',
    },
  },

  rose: {
    light: {
      primary: '#e11d48',
      primaryHover: '#be123c',
      primaryForeground: '#ffffff',
      secondary: '#ffe4e6',
      secondaryHover: '#fecdd3',
      secondaryForeground: '#881337',
      background: '#ffffff',
      foreground: '#4c0519',
      surface: '#fff1f2',
      surfaceHover: '#ffe4e6',
      border: '#fecdd3',
      text: '#4c0519',
      textMuted: '#9f1239',
      ring: '#f43f5e',
    },
    dark: {
      primary: '#f43f5e',
      primaryHover: '#fb7185',
      primaryForeground: '#ffffff',
      secondary: '#881337',
      secondaryHover: '#9f1239',
      secondaryForeground: '#ffe4e6',
      background: '#2a0812',
      foreground: '#fff1f2',
      surface: '#4c0519',
      surfaceHover: '#881337',
      border: '#9f1239',
      text: '#fff1f2',
      textMuted: '#fda4af',
      ring: '#fb7185',
    },
  },

  midnight: {
    light: {
      primary: '#0f172a',
      primaryHover: '#1e293b',
      primaryForeground: '#ffffff',
      secondary: '#e2e8f0',
      secondaryHover: '#cbd5e1',
      secondaryForeground: '#0f172a',
      background: '#f8fafc',
      foreground: '#0f172a',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      border: '#cbd5e1',
      text: '#0f172a',
      textMuted: '#64748b',
      ring: '#0f172a',
    },
    dark: {
      primary: '#38bdf8',
      primaryHover: '#7dd3fc',
      primaryForeground: '#0f172a',
      secondary: '#1e293b',
      secondaryHover: '#334155',
      secondaryForeground: '#f8fafc',
      background: '#030712',
      foreground: '#f8fafc',
      surface: '#0b0f19',
      surfaceHover: '#111827',
      border: '#1f2937',
      text: '#f8fafc',
      textMuted: '#9ca3af',
      ring: '#38bdf8',
    },
  },
};

export function resolveThemeColors(
  themeInput: ThemePreset | ThemeColors,
  isDark: boolean
): ThemeColors {
  if (typeof themeInput === 'string') {
    const preset = themePresets[themeInput] || themePresets.default;
    return isDark ? preset.dark : preset.light;
  }

  // If user passed custom object, merge with default preset defaults
  const base = isDark ? themePresets.default.dark : themePresets.default.light;
  return {
    ...base,
    ...themeInput,
  };
}
